version: 2
jobs:
  green-job:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: go get -u github.com/raviqqe/muffet && muffet http://www.nomin.cloud/
  blue-job:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run: whoami
workflows:
  version: 2
  build_and_test:
    jobs:
      - green-job
      - blue-job
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - green-job
