version: 2
jobs:
  green-job:
    docker:
      - image: fedora:latest
    steps:
      - checkout
      - run: whoami
  blue-job:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run: whoami
workflows:
  version: 2
  build_and_test:
    jobs:
      - green-job
      - blue-job
